PR : For deliver task 3 arm sprint led control v2.0
sherifkhadr/SPRINTS_Automotive_Software_Bootcamp pull request #2
Opened 2023-06-19 20:51 UTC by sherifkhadr

2023-06-20 14:39 UTC, Hala-Abdelkader requested changes

2023-06-20 14:39 UTC, Hala-Abdelkader commented on 07_Sprint_Twelve/02_RGB_LED_CONTROL_V2.0/00_Project/RGB_LED_SEQUANCE_V2.0/APPLICATION/app.c
> +		if(pressCounter == 1)
You shouldn't use magic numbers

2023-06-20 21:43 UTC, sherifkhadr commented on 07_Sprint_Twelve/02_RGB_LED_CONTROL_V2.0/00_Project/RGB_LED_SEQUANCE_V2.0/APPLICATION/app.c
> +		if(pressCounter == 1)
Done Now You Can Check The Last Commit

2023-06-20 21:44 UTC, sherifkhadr commented
Done Now You Can Check The Last Commit

On Tue, 20 Jun 2023 at 17:39, Hala-Abdelkader ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In
> 07_Sprint_Twelve/02_RGB_LED_CONTROL_V2.0/00_Project/RGB_LED_SEQUANCE_V2.0/APPLICATION/app.c
> <https://github.com/sherifkhadr/SPRINTS_Automotive_Software_Bootcamp/pull/2#discussion_r1235368321>
> :
>
> > +		if(btn == PUSH_BTN_STATE_PRESSED)
> +		{
> +			while(btn == PUSH_BTN_STATE_PRESSED)
> +			{
> +				 PUSH_BTN_read_state(&a_pushBtnCfgPins[0] , &btn);
> +				
> +				for(VUint8_t i=0;i<200;i++)
> +				{
> +					for(VUint8_t j =0 ; j<100;j++);
> +				}
> +			}
> +		
> +			 pressCounter++;
> +		}
> +		
> +		if(pressCounter == 1)
>
> You shouldn't use magic numbers
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sherifkhadr/SPRINTS_Automotive_Software_Bootcamp/pull/2#pullrequestreview-1488314844>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASJSQSOJQPFLFRRWMQXCS6LXMGYZFANCNFSM6AAAAAAZMMPQHU>
> .
> You are receiving this because you authored the thread.Message ID:
> <sherifkhadr/SPRINTS_Automotive_Software_Bootcamp/pull/2/review/1488314844
> @github.com>
>

2023-06-21 11:34 UTC, Hala-Abdelkader commented on 07_Sprint_Twelve/02_RGB_LED_CONTROL_V2.0/00_Project/RGB_LED_SEQUANCE_V2.0/APPLICATION/app.c
> +		if(pressCounter == 1)
Great, well done.

2023-06-22 16:03 UTC, merged